version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: capstone_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 826As6523$$$
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: capstone_fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=826As6523$$$
      - DB_PORT=5432
      - SECRET_KEY=super-secret-key-change-this-in-production
    depends_on:
      - db

volumes:
  postgres_data: